### ISSUE TITLE
add where and which command with flags

### ISSUE THREAD

**Issue by Cirediallo** [Amit00790/Linux-commands#20]

**Comment by Cirediallo** [comment]
@Amit00790 I have a permission denied error when pushing is there anything I need to know ?

**Comment by pnchinmay** [comment]
Did u fork first??

**Comment by Cirediallo** [comment]
sorry I cloned it that's why I suppose

**Comment by pnchinmay** [comment]
https://www.google.com/search?q=how+to+contribute+to+a+repository+github&rlz=1C1EXJR_enIN915IN915&oq=how+to+contribute+in+a+repo&aqs=chrome.1.69i57j0.19656j1j1&sourceid=chrome&ie=UTF-8

**Comment by pnchinmay** [comment]
For further queries, no need to open another issue
Issues only for project related new setups
PRs are submitted through the same issue which it corresponds
Make sure to update on issue page about the commands in your PR
Check issue #3
